### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by ztt0821** [titu1994/neural-image-assessment#16]
I run the train_model, and find some problems:
Traceback (most recent call last):
File "/home/ztt/下载/neural-image-assessment-master/train_model.py", line 196, in
main()
File "/home/ztt/下载/neural-image-assessment-master/train_model.py", line 188, in main
initial_epoch=0
File "/home/ztt/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
return func(*args, **kwargs)
File "/home/ztt/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/training.py", line 2145, in fit_generator
generator_output = next(output_generator)
File "/home/ztt/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/utils/data_utils.py", line 561, in get
six.raise_from(StopIteration(e), e)
File "", line 3, in raise_from
StopIteration: [Errno 2] No such file or directory: 's:\datasets\AVA_dataset\images/950742.jpg'

**Comment by tfriedel** [comment]
Edit config.py.
Add the directory of your AVA dataset in this line:
base_images_path = Path(r's:\datasets\AVA_dataset\images')

ztt0821 <notifications@github.com> schrieb am Di., 30. Jan. 2018, 10:25:
