### ISSUE TITLE
i face the error when using it for other dataset not AVA

### ISSUE THREAD

**Issue by sucream1004** [titu1994/neural-image-assessment#23]
hello!

i tried to train with vgg16 structure.
but, after epochs are done, error codes come out like this.
and the data's format is same as AVA.

Exception ignored in: <generator object val_generator at 0x7f878d041728>
Traceback (most recent call last):
  File "/home/kpark2/neural-image-assessment/utils/data_loader.py", line 160, in val_generator
    yield (X_batch, y_batch)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1558, in __exit__
    self._default_graph_context_manager.__exit__(exec_type, exec_value, exec_tb)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4973, in get_controller
    context.context_stack.pop()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/context.py", line 100, in pop
    self.stack.pop()
IndexError: pop from empty list
Exception ignored in: <generator object train_generator at 0x7f878d0416d0>
Traceback (most recent call last):
  File "/home/kpark2/neural-image-assessment/utils/data_loader.py", line 125, in train_generator
    yield (X_batch, y_batch)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1558, in __exit__
    self._default_graph_context_manager.__exit__(exec_type, exec_value, exec_tb)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4973, in get_controller
    context.context_stack.pop()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/context.py", line 100, in pop
    self.stack.pop()
IndexError: pop from empty list

help me!

**Comment by sucream1004** [comment]
sorry it actually worked i misunderstood

**Comment by Xiaocong6** [comment]
hi~
i met the same error, how do you solve it?

**Comment by syagmur** [comment]
I had the same error and spend more than a day to debug it. In case someone looks for a solution, I have changed the last part of the training functions from: 

model.fit_generator(train_generator(batchsize=batchsize),
                    steps_per_epoch=(250000. // batchsize),
                    epochs=epochs, verbose=1, callbacks=callbacks,
                    validation_data=val_generator(batchsize=batchsize),
                    validation_steps=(5000. // batchsize))

to:

train_data_generator = train_generator(batchsize=batchsize)
val_data_generator = val_generator(batchsize=batchsize)
model.fit_generator(train_data_generator,
                    steps_per_epoch=(250000. // batchsize),
                    epochs=epochs, verbose=1, callbacks=callbacks,
                    validation_data=val_data_generator,
                    validation_steps=(5000. // batchsize))

I don't know why it works this way but solved my problem. Hope that helps!
