### ISSUE TITLE
Error when I run train_mobilenet.py

### ISSUE THREAD

**Issue by weijjzhang** [titu1994/neural-image-assessment#27]
I meet error when train mobilenet according to your guide. Please help me, thanks~

Traceback (most recent call last):
  File "train_mobilenet.py", line 88, in <module>
    validation_steps=(5000. // batchsize))
  File "/home/zw/work/NIMA/venv/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/zw/work/NIMA/venv/local/lib/python2.7/site-packages/keras/engine/training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "/home/zw/work/NIMA/venv/local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/home/zw/work/NIMA/venv/local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "/home/zw/work/NIMA/neural-image-assessment/utils/data_loader.py", line 102, in train_generator
    train_dataset = tf.data.Dataset().from_tensor_slices((train_image_paths, train_scores))
TypeError: Can't instantiate abstract class Dataset with abstract methods _as_variant_tensor, output_shapes, output_types

The dataset print result is as below:
('Train set size : ', (250508,), (250508, 10))
('Val set size : ', (5000,), (5000, 10))
Train and validation datasets ready !

**Comment by weijjzhang** [comment]
python version is not suitable
