### ISSUE TITLE
problem at training

### ISSUE THREAD

**Issue by jiazhenggod** [titu1994/neural-image-assessment#31]
Hello, i encountered the following error when using train_nasnet_mobile.py. I actually encountered the same error when using all the other training models. Evaluate models worked very well.

Total params: 4,280,286
Trainable params: 10,570
Non-trainable params: 4,269,716
__________________________________________________________________________________________________
Epoch 1/20
Traceback (most recent call last):
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 947, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype float64: 'Tensor("arg0:0", shape=(), dtype=float64)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_nasnet_mobile.py", line 93, in <module>
    validation_steps=(5000. // batchsize))
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/keras/engine/training_generator.py", line 155, in fit_generator
    generator_output = next(output_generator)
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "/Users/jiazhengyuan/Documents/workspace/neural-image-assessment/utils/data_loader.py", line 101, in train_generator
    train_dataset = train_dataset.map(parse_data, num_parallel_calls=2)
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 853, in map
    return ParallelMapDataset(self, map_func, num_parallel_calls)
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1870, in __init__
    super(ParallelMapDataset, self).__init__(input_dataset, map_func)
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1839, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 484, in add_to_graph
    self._create_definition_if_needed()
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 319, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 336, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1802, in tf_map_func
    ret = map_func(*nested_args)
  File "/Users/jiazhengyuan/Documents/workspace/neural-image-assessment/utils/data_loader.py", line 61, in parse_data
    image = tf.read_file(filename)
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 528, in read_file
    "ReadFile", filename=filename, name=name)
  File "/Users/jiazhengyuan/venv3.62/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 533, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'filename' of 'ReadFile' Op has type float64 that does not match expected type of string.

**Comment by titu1994** [comment]
In the list of filenames you are passing to the reader, it is getting a floating point value for some reason instead of a list of strings. Check by printing out the contents of the files list and see if some floating point values are somehow there.
