### ISSUE TITLE
error at the last epoch

### ISSUE THREAD

**Issue by jiazhenggod** [titu1994/neural-image-assessment#32]
Epoch 00020: val_loss did not improve from 0.04966
Exception ignored in: <generator object val_generator at 0x7f588c71da20>
Traceback (most recent call last):
  File "/home/tiger/jiazheng/neural-image-assessment/utils/data_loader.py", line 158, in val_generator
    yield (X_batch, y_batch)
  File "/home/tiger/jiazheng/venv34/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1596, in __exit__
    self._default_graph_context_manager.__exit__(exec_type, exec_value, exec_tb)
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tiger/jiazheng/venv34/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 5267, in get_controller
    context.context().context_switches.pop()
  File "/home/tiger/jiazheng/venv34/lib/python3.4/site-packages/tensorflow/python/eager/context.py", line 136, in pop
    self.stack.pop()
IndexError: pop from empty list
Exception ignored in: <generator object train_generator at 0x7f58ac2835e8>
Traceback (most recent call last):
  File "/home/tiger/jiazheng/neural-image-assessment/utils/data_loader.py", line 123, in train_generator
    yield (X_batch, y_batch)
  File "/home/tiger/jiazheng/venv34/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1596, in __exit__
    self._default_graph_context_manager.__exit__(exec_type, exec_value, exec_tb)
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tiger/jiazheng/venv34/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 5267, in get_controller
    context.context().context_switches.pop()
  File "/home/tiger/jiazheng/venv34/lib/python3.4/site-packages/tensorflow/python/eager/context.py", line 136, in pop
    self.stack.pop()
IndexError: pop from empty list

after the last epoch, this error happened. I checked the dataset, the ava.txt matches the training images.  all the epochs before were good. Thanks!

**Comment by titu1994** [comment]
This code wasn't built for eager execution mode on Tensorflow, that may be one of the issues. Otherwise see whether you can drop theast batch inside the dataset.batch method. Maybe that will fix it.

**Comment by Xiaocong6** [comment]
hi, I met the same error. How do you solve it?
Hope for your help. Thanks!

**Comment by ranju2015** [comment]
Same error I am getting. I have not used eager execution mode. 

Epoch 00020: val_loss did not improve from 0.08821
Exception ignored in: <generator object train_generator at 0x7f7ee96fb308>
Traceback (most recent call last):
  File "/home/bigdata/s2830250/nima-master-titu1994/utils/data_loader.py", line 128, in train_generator
    yield (X_batch, y_batch)
  File "/home/bigdata/s2830250/rvenv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1587, in __exit__
    self._default_graph_context_manager.__exit__(exec_type, exec_value, exec_tb)
  File "/usr/local/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/bigdata/s2830250/rvenv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5233, in get_controller
    context.context().context_switches.pop()
  File "/home/bigdata/s2830250/rvenv/lib/python3.5/site-packages/tensorflow/python/eager/context.py", line 141, in pop
    self.stack.pop()
IndexError: pop from empty list

**Comment by ranju2015** [comment]
> This code wasn't built for eager execution mode on Tensorflow, that may be one of the issues. Otherwise see whether you can drop theast batch inside the dataset.batch method. Maybe that will fix it.

Do you think the training sample needs to be divisible by 200 if my batchsize is 200?  My dataset remainder is 21 if I divide total samples by 200.

**Comment by ranju2015** [comment]
> Epoch 00020: val_loss did not improve from 0.04966
> Exception ignored in: <generator object val_generator at 0x7f588c71da20>
> Traceback (most recent call last):
> File "/home/tiger/jiazheng/neural-image-assessment/utils/data_loader.py", line 158, in val_generator
> yield (X_batch, y_batch)
> File "/home/tiger/jiazheng/venv34/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1596, in **exit**
> self._default_graph_context_manager.**exit**(exec_type, exec_value, exec_tb)
> File "/usr/lib/python3.4/contextlib.py", line 77, in **exit**
> self.gen.throw(type, value, traceback)
> File "/home/tiger/jiazheng/venv34/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 5267, in get_controller
> context.context().context_switches.pop()
> File "/home/tiger/jiazheng/venv34/lib/python3.4/site-packages/tensorflow/python/eager/context.py", line 136, in pop
> self.stack.pop()
> IndexError: pop from empty list
> Exception ignored in: <generator object train_generator at 0x7f58ac2835e8>
> Traceback (most recent call last):
> File "/home/tiger/jiazheng/neural-image-assessment/utils/data_loader.py", line 123, in train_generator
> yield (X_batch, y_batch)
> File "/home/tiger/jiazheng/venv34/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1596, in **exit**
> self._default_graph_context_manager.**exit**(exec_type, exec_value, exec_tb)
> File "/usr/lib/python3.4/contextlib.py", line 77, in **exit**
> self.gen.throw(type, value, traceback)
> File "/home/tiger/jiazheng/venv34/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 5267, in get_controller
> context.context().context_switches.pop()
> File "/home/tiger/jiazheng/venv34/lib/python3.4/site-packages/tensorflow/python/eager/context.py", line 136, in pop
> self.stack.pop()
> IndexError: pop from empty list
> 
> after the last epoch, this error happened. I checked the dataset, the ava.txt matches the training images. all the epochs before were good. Thanks!

Did you solve the problem?

**Comment by ranju2015** [comment]
> This code wasn't built for eager execution mode on Tensorflow, that may be one of the issues. Otherwise see whether you can drop theast batch inside the dataset.batch method. Maybe that will fix it.

Would you please elaborate this point little more? I am stuck at this point.

**Comment by Jackyinuo** [comment]
> > This code wasn't built for eager execution mode on Tensorflow, that may be one of the issues. Otherwise see whether you can drop theast batch inside the dataset.batch method. Maybe that will fix it.
> 
> Would you please elaborate this point little more? I am stuck at this point.

HI， I have been stuck in this error, would you addressed this error???
