### ISSUE TITLE
when i train model on TID2013 dataset,something went wrong

### ISSUE THREAD

**Issue by leeqiaogithub** [titu1994/neural-image-assessment#48]
I want to train a model on tid2013,so i changed some details in  the script of data_loader.py.but i got an error:
Traceback (most recent call last):
  File "train_mobilenet_tid.py", line 90, in <module>
    validation_steps=(500. // batchsize))
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: Can't instantiate abstract class Dataset with abstract methods _as_variant_tensor, output_classes, output_shapes, output_types
I am so confused of this error,could you help me with this?

**Comment by titu1994** [comment]
For different datasets, you need to pass in the the correct shapes of the batches, since tid and AVA have different numver of samples.

**Comment by leeqiaogithub** [comment]
@titu1994 I already changed the script of data_loader.py,the shape of training set and val set as well.I am not sure what you mean about the shapes of the batches.

**Comment by titu1994** [comment]
Hmm that is weird. I don't know the reason for this error then. I'll search if there is any answer on Google.

**Comment by leeqiaogithub** [comment]
@titu1994  i run your code ——train_mobilenet.py,there was the same error

**Comment by yfor1008** [comment]
@leeqiaogithub  have you solved this error?

**Comment by dothuhahb98** [comment]
can anyone have TID2013 and TID2008 datasets, i really need to use it for training but i can find it in the internet. Thank you so much
