### ISSUE TITLE
train mobilenet test error

### ISSUE THREAD

**Issue by aijianiula0601** [titu1994/neural-image-assessment#6]
it encouter below error when I training test data with 45 images for train_dataset and 25 images for val_dataset.

------------------- validation exception!
Exception ignored in: <generator object DataSetLoader.val_generator at 0x10eb6d888>
Traceback (most recent call last):
  File "/Users/jia/IdeaProjects/lizhifm_projects/image_quality_assessment/image_assessment/data/dataset_loader.py", line 196, in val_generator
    yield (x_batch, y_batch)
  File "/Users/jia/.virtualenvs/tensorflow1.3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1507, in __exit__
    exec_type, exec_value, exec_tb)
  File "/Users/jia/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/jia/.virtualenvs/tensorflow1.3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3972, in get_controller
    if self.stack[-1] is not default:
IndexError: list index out of range
------------------- train exception!
Exception ignored in: <generator object DataSetLoader.train_generator at 0x10eb6d830>
Traceback (most recent call last):
  File "/Users/jia/IdeaProjects/lizhifm_projects/image_quality_assessment/image_assessment/data/dataset_loader.py", line 147, in train_generator
    yield (x_batch, y_batch)
  File "/Users/jia/.virtualenvs/tensorflow1.3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1507, in __exit__
    exec_type, exec_value, exec_tb)
  File "/Users/jia/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/jia/.virtualenvs/tensorflow1.3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3972, in get_controller
    if self.stack[-1] is not default:
IndexError: list index out of range
Exception ignored in: <generator object get_controller at 0x10eb6d9e8>
Traceback (most recent call last):
  File "/Users/jia/.virtualenvs/tensorflow1.3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3972, in get_controller
    if self.stack[-1] is not default:
IndexError: list index out of range
Exception ignored in: <generator object get_controller at 0x112e5e360>
Traceback (most recent call last):
  File "/Users/jia/.virtualenvs/tensorflow1.3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3972, in get_controller
    if self.stack[-1] is not default:
IndexError: list index out of range

**Comment by titu1994** [comment]
Train and test set are supposed to be from the AVA dataset, with 250000 train images and 5000 validation images. 

Since your batch size is 200, and you try to load 200 images, but you have only 25 for Val and 45 for train, it crashes. 

Change the model.fit_generator line and the batchsize to be suitable to your Dataset. 

Also, with such few images, you are most probably going to overfit and reduce the network performance.
